# Caso Práctico: Neurona de McCulloch y Pitts

## 2. Aplicando la MPNeuron a un caso práctico real

### 2.1. Conjunto de datos

Esta es una copia de los conjuntos de datos de UCI ML Breast Cancer Wisconsin (Diagnóstico). https://goo.gl/U2Uwz2

Las características de entrada se calculan a partir de una imagen digitalizada de un aspirado de aguja fina (FNA) de una masa mamaria. Describen las características de los núcleos celulares presentes en la imagen.

El plano de separación descrito anteriormente se obtuvo utilizando el método de árbol de múltiples superficies (MSM-T) [K. P. Bennett, "Construcción de un árbol de decisión mediante programación lineal". Proceedings of the 4th Midwest Artificial Intelligence and Cognitive Science Society, pp. 97-101, 1992], un método de clasificación que utiliza la programación lineal para construir un árbol de decisión. Los rasgos relevantes se seleccionaron mediante una búsqueda exhaustiva en el espacio de 1-4 rasgos y 1-3 planos de separación.

El programa lineal real utilizado para obtener el plano de separación en el espacio tridimensional es el que se describe en: [K. P. Bennett y O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].

Esta base de datos también está disponible a través del servidor ftp UW CS:

ftp ftp.cs.wisc.edu cd math-prog/cpo-dataset/machine-learn/WDBC/

### Referencias

* W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on Electronic Imaging: Science and Technology, volume 1905, pages 861-870, San Jose, CA, 1993.
* O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and prognosis via linear programming. Operations Research, 43(4), pages 570-577, July-August 1995.
* W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994) 163-171.

### 2.3. Lectura del conjunto de datos

In [2]:
from sklearn.datasets import load_breast_cancer

breast_cancer = load_breast_cancer()


In [3]:
X = breast_cancer.data

In [4]:
Y = breast_cancer.target

In [5]:
dir(breast_cancer)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

### 2.2. Visualización del conjunto de datos

In [12]:
import pandas as pd
df = pd.DataFrame(X, columns = breast_cancer.feature_names)

### 2.3. División del conjunto de datos

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, Y, stratify = Y)
print("Tamaño del conjunto de datos de entrenamiento:", len(X_train))
print("Tamaño del conjunto de datos de prueba:", len(X_test))

Tamaño del conjunto de datos de entrenamiento: 426
Tamaño del conjunto de datos de prueba: 143


### 2.4. Implementación de una MPNeuron más avanzada

In [13]:
import numpy as np
from sklearn.metrics import accuracy_score

class MPNeuron:
    def __init__(self):
        self.threshold = None

    def model(self, x):
          # input : [x1,x2,x3,.....,xn][0||1]
        z = sum(x)
        return (z >= self.threshold)

    def predict(self, X):
          # input : [[1,0,1,0],[0,1,0,1]]
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)

    def fit(self, X, Y):
        accuracy = {}
        # Seleccionar un threshold entre el # de caracteristicas de entrada 
        for th in range(X.shape[1] + 1):
            self.threshold = th
            Y_pred = self.predict(X)
            accuracy[th] = accuracy_score(Y_pred, Y)

        #Seleccionar el threshold que de mejores resultados 
        self.threshold = max(accuracy, key=accuracy.get)

Seguimos teniendo un problema debido a que en nuestro conjunto de datos las características de entrada reciben valores continuos, sin embargo, nuestra MPNeuron solo procesa características de entrada con valor binario

In [17]:
# Para transformar un valor a binario
import matplotlib.pyplot as plt
print(pd.cut([0.04,2,3.1,5,6,0.02,0.6],bins=2, labels=[0,1]))
plt.hist([0.04,2,4,5,6,0.02,0.6],bins=2)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [16]:
# Transformamos las caracteríticas de entrada a un valor binario
X_train_bin = X_train.apply(pd.cut, bins=2, labels=[1,0])
X_test_bin = X_test.apply(pd.cut, bins=2, labels=[1,0])

X_train_bin

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
54,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,1,1,1,0,1,1
285,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
69,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
343,0,1,0,0,1,1,1,0,1,1,...,0,0,0,1,1,1,1,0,1,1
259,1,0,1,1,1,1,1,1,1,1,...,1,0,1,1,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,1,1,1,1,0,0,1,1,1,0,...,1,1,1,1,0,1,1,1,1,0
373,0,1,0,0,1,1,1,1,1,1,...,0,1,0,0,0,1,1,0,1,1
55,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
115,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,1


In [18]:
# Instanciamos el modelo MPNeuron
mp_neurona = MPNeuron()

# Encontramos el threshold óptimo
mp_neurona.fit(X_train_bin.to_numpy(), y_train)

In [19]:
# Threshold óptimo seleccionado
mp_neurona.threshold

28

In [20]:
# Realizamos predicciones para ejemplos nuevos que no se encuentran en el conjunto de datos de entrenamiento
Y_Pred = mp_neurona.predict(X_test_bin.to_numpy())

In [21]:
Y_Pred

array([False, False, False,  True,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True, False,  True, False,
       False,  True, False, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True, False, False,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True, False,  True, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True, False,

In [23]:
# Calculamos la exactitud de nuestra predicción
accuracy_score(y_test, Y_Pred)

0.7972027972027972

In [24]:
# Calculamos la matriz de confusión
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, Y_Pred)

array([[45,  8],
       [21, 69]])