# Caso practico: Neruona de McCulloch y Pitts

## 1.- Implementacion de MPNeuron

In [24]:
import numpy as np

### Declaración de la clase MPNeuron

In [25]:
class MPNeuron:
    def __init__(self):
        self.threshold = None

    def model(self, x):
          # input : [x1,x2,x3,.....,xn][0||1]
        z = sum(x)
        return (z >= self.threshold)

    def predict(self, X):
          # input : [[1,0,1,0],[0,1,0,1]]
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)
        

### Instanciamos a la clase

In [26]:
mp_neurona = MPNeuron()

In [27]:
mp_neurona.threshold=3

In [28]:
mp_neurona.predict([[1,1,0,0],[1,1,0,1],[1,0,0,0]])

array([False,  True, False])

### Compuertas lógicas AND

In [33]:
mp_neurona.thresshold = 2
mp_neurona.predict([[0, 0, 1, 1], [0, 1, 0, 1]])

array([False, False])

### Implementando Compuertas lógicas OR

In [31]:
mp_neurona.thresshold = 1
mp_neurona.predict([[0, 0, 1, 1], [0, 0, 0, 1]])

array([False, False])